---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: nginx-1
        image: nginx:1.12
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1            
            initialDelaySeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 100Mi 
          limits:
            cpu: 100m
            memory: 200Mi
